# Generated by Django 3.1.7 on 2021-02-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='daily_report',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='extra_food_number',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='personnel_error',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='report_date',
        ),
        migrations.AddField(
            model_name='report',
            name='daily_report',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='extra_food_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='personnel_error_report',
            field=models.TextField(null=True),
        ),
    ]
