# Generated by Django 3.1.7 on 2021-02-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20210222_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='daily_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='personnel_error_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
