# Generated by Django 3.1.7 on 2021-02-23 03:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20210222_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='cook_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='distribution_report',
        ),
        migrations.AddField(
            model_name='cook',
            name='report',
            field=models.ForeignKey(
                default='0', on_delete=django.db.models.deletion.CASCADE, to='kitchen.report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='report',
            field=models.ForeignKey(
                default='0', on_delete=django.db.models.deletion.CASCADE, to='kitchen.report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
