# Generated by Django 3.1.7 on 2021-02-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20210223_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='personnel_error_report',
            new_name='personnel_mistake_report',
        ),
    ]
