# Generated by Django 3.1.7 on 2021-02-24 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0005_auto_20210223_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cook',
            name='cook_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_chef', to='kitchen.chef'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='preparation_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_chef', to='kitchen.chef'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distributor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor1', to='kitchen.distributor'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distributor2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor2', to='kitchen.distributor'),
        ),
    ]
