# Generated by Django 3.1.7 on 2021-03-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20210224_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='extra_food_number',
        ),
        migrations.AddField(
            model_name='cook',
            name='number_of_extra_foods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cook',
            name='number_of_foods',
            field=models.IntegerField(default=0),
        ),
    ]
