# Generated by Django 3.1.7 on 2021-03-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20210306_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='cook_chef',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cook_chef', to='kitchen.chef'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cook',
            name='food',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.food'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='preparation_chef',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preparation_chef', to='kitchen.chef'),
            preserve_default=False,
        ),
    ]
