# Generated by Django 3.1.7 on 2021-03-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_mistake_report', models.TextField(blank=True, null=True)),
                ('daily_report', models.TextField(blank=True, null=True)),
                ('step', models.IntegerField(default=0)),
                ('report_date', models.DateField(null=True, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor1', to='kitchen.distributor')),
                ('distributor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor2', to='kitchen.distributor')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.meal')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.report')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.section')),
            ],
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_foods', models.IntegerField(default=0)),
                ('number_of_extra_foods', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook_chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_chef', to='kitchen.chef')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.food')),
                ('preparation_chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_chef', to='kitchen.chef')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.report')),
            ],
        ),
    ]
