# Generated by Django 3.1.7 on 2021-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20210308_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_meme', 'can_nnn'),)},
        ),
    ]
