# Generated by Django 3.1.7 on 2021-03-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20210328_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
