# Generated by Django 3.1.7 on 2021-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='User_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
