# Generated by Django 3.1.7 on 2021-04-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('add_report_in_kitchen', 'add report in kitchen'), ('manage_report_in_kitchen', 'manage report in kitchen'))},
        ),
    ]
