# Generated by Django 3.1.7 on 2021-04-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210418_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_add_report_in_kitchen', 'Can add report in kitchen'), ('can_manage_report_in_kitchen', 'Can manage report in kitchen'))},
        ),
    ]
