# Generated by Django 3.1.7 on 2021-04-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210418_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('add_report_in_kitchen', 'Can add report in kitchen'), ('manage_report_in_kitchen', 'Can manage report in kitchen'))},
        ),
    ]
