# Generated by Django 3.1.7 on 2021-04-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20210403_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(1, 'حضوری'), (2, 'غیر حضوری')], default=1),
        ),
    ]
